# -*- coding: utf-8 -*-
"""OOP Programming Exec.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7z94erpjJhpnqKnuc4uT5nXSDzeLd1N
"""

class FoodOrder:
    def __init__(self, foodname, standardprice, amount):
        self.foodname = foodname
        self.__standardprice = self.PriceList()
        self.amount = amount
        self.__calcPrice = self.foodCalc()

def PriceList(self):
            if self.food_name == 'Dry Cured Iberian Ham':
                self.__standardprice = 177.80
            elif self.food_name == 'Wagyu Steaks':
                self.__standardprice = 450.00
            elif self.food_name == 'Matsutake Mushrooms':
                self.__standardprice = 272.00
            elif self.food_name == 'Kopi Luwak Coffee':
                self.__standardprice = 306.50
            elif self.food_name == 'Moose Cheese':
                self.__standardprice = 487.20
            elif self.food_name == 'White Truffles':
                self.__standardprice = 3600.00
            elif self.food_name == 'Blue Fin Tuna':
                self.__standardprice = 3603.00
            elif self.food_name == 'Le Bonnotte Potatoes':
                self.__standardprice = 270.81
            else:
                self.__standardprice = 0.00
            return self.__standardprice
           
def foodCalc(self):
     return self.amount * self.PriceList(),2