# -*- coding: utf-8 -*-
"""OOP Exec Driver.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T0py16TLXiTPJ2Br2LwOlkirenlDhJE6
"""

from food_order import FoodOrder

def create_food_order_list():
    food_orders = []
    num_items = int(input("How many items will you order today? "))
    while num_items < 1:
        print("Number of items must be at least 1.")
        num_items = int(input("How many items will you order today? "))

    for i in range(1, num_items + 1):
        print(f"Item #{i}-")
        food_name = input("Enter food: ")
        amount = float(input("Enter amount of pounds: "))
        while amount <= 0:
            print("Amount of pounds must be greater than 0.")
            amount = float(input("Enter amount of pounds: "))

        # Instantiate the FoodOrder object correctly
        order = FoodOrder(food_name, amount)
        food_orders.append(order)

    return food_orders

def display_food_order_list(food_orders):
    for food_order in food_orders:
        print(food_order)
        print()

def calculate_total_cost(food_orders):
    total_cost = sum(food_order.get_calculated_price() for food_order in food_orders)
    return total_cost

def main():
    orders = create_food_order_list()
    print("\nHere's a summary of the items purchased:")
    display_food_order_list(orders)
    total_cost = calculate_total_cost(orders)
    print(f"Total cost: ${total_cost:.2f}")

if __name__ == "__main__":
    main()